### ISSUE TITLE
Handle and ignore remote urls 

### ISSUE THREAD

**Issue by vrishab** [donaghhorgan/rhythmbox-plugins-open-containing-folder#10]
After applying patch in  [ https://bugzilla.gnome.org/show_bug.cgi?id=773858 ]( https://bugzilla.gnome.org/show_bug.cgi?id=773858 ) the following error happens if the location is a remote url ( podcast not downloaded yet )

```
gvfs-open: file:/play.podtrac.com/espn-espnucollegebasketball/c.espnradio.com/s:J1X3L/audio/2708236: error opening location: Error when getting information for file '/play.podtrac.com/espn-espnucollegebasketball/c.espnradio.com/s:J1X3L/audio/2708236': No such file or directory
ERROR:root:Could not open folder
Traceback (most recent call last):
  File "/home/dev/.local/share/rhythmbox/plugins/rhythmbox-plugins-open-containing-folder/OpenContainingFolder.py", line 63, in open_folder
    subprocess.check_call(['xdg-open', dirpath])
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['xdg-open', 'file:/play.podtrac.com/espn-espnucollegebasketball/c.espnradio.com/s:J1X3L/audio/2708236']' returned non-zero exit status 4

```

**Comment by vrishab** [comment]
RB.uri_is_local (uri) should help.

https://developer.gnome.org/rhythmbox/stable/rhythmbox-rb-file-helpers.html#rb-uri-is-local
